#========================================================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Use Releases file to packaging
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#========================================================================================================================

name: test release

on:
  repository_dispatch:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
 

    - name: test
      id: build
     
      run: |
        echo "release test " >release.txt
    


    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@v1
      with:
        tag: test
        artifacts: release.txt
      
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### **test rlease**
 
          
