name: Build test

on:
  repository_dispatch:
  workflow_dispatch:
 
     
env:
  UPLOAD_COWTRANSFER: false
  RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build for N1
    strategy:
      fail-fast: false
    

 
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |     
        version=$(curl -s "https://api.github.com/repos/freedyYang/N1_OpenWrt/tags" |grep -o "ARM")
        
        #echo "version=$version"  >> $GITHUB_ENV
        #echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")"  >> $GITHUB_ENV
        
        echo "version=$version"
        ls 
        pwd
        mkdir freedy
        sudo chmod  -R 777 freedy
        ls
        #cp -r ${FLIPPY_NAME}/opt/* /opt
                
  
                
    - name: Check Files
      run: |
        cd freedy
        ls
                

   
 

  
  
  
